AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  etf-digest-lambda

  Sample SAM Template for etf-digest-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  EtfDigestFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: EtfDigestFunction
      Handler: etfdigest.EtfUpdateHandler::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        EtfDigest:
          Type: EventBridgeRule # More info about EventBridgeRule Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#eventbridgerule
          Properties:
            Pattern:
              source:
                - aws.ec2
              detail-type:
                - EC2 Instance State-change Notification

Outputs:
  EtfDigestFunction:
    Description: "Etf Digest Lambda Function ARN"
    Value: !GetAtt EtfDigestFunction.Arn
  EtfDigestFunctionIamRole:
    Description: "Implicit IAM Role created for Etf Digest function"
    Value: !GetAtt EtfDigestFunctionRole.Arn
